version: '3'
services:
  rethinkdb:
    image: 'rethinkdb:latest'
    ports:
     - "28015:28015" # client driver connections
     - "29015" # Intracluster connection
     - "2880:8080" # http administration interface
    volumes:
     - ./docker/rethinkdb/data:/data
  pushpin:
    build: ./docker/pushpin
    image: my/pushpin
    volumes: 
      - ./docker/pushpin/routes:/etc/pushpin/routes
    ports:
        - "7999:7999"
        - "5560-5563:5560-5563"
  devapi:
    image: backend/dev
    build: 
      context: ./backend 
      dockerfile: ./dev.Dockerfile
    links:
      - rethinkdb
    
    volumes: 
      - ./backend:/usr/src/help/backend
    ports:
      - "28080:28080"

