version: '3'
services:
  # DATABASE
  rethinkdb:
    image: 'rethinkdb:latest'
    volumes: # persist data
     - ./docker/rethinkdb/data:/data
  
  # fancy REST -> Realtime API middleware
  pushpin:
    build: ./docker/pushpin
    image: my/pushpin
    volumes: 
      - ./docker/pushpin/routes:/etc/pushpin/routes
  
  # REST API with pushpin integration
  api:
    image: backend/dev
    build: 
      context: ./backend 
      dockerfile: ./prod.Dockerfile
    depends_on:
      - rethinkdb
    
    volumes: 
      - ./backend:/usr/src/help/backend
  
  caddy:
    image: "wemakeservices/caddy-docker:latest"
    volumes:
      - ./docker/caddy/certs:/root/.caddy  # to save certificates on disk
      - ./docker/caddy/Caddyfile.prod:/etc/Caddyfile  # to mount custom Caddyfile
    ports:
      - "80:80"
      - "443:443"

