# overrides with dev environment settings
version: '3'
services:
  # fakes som domain name stuff for development
  dns:
    image: 'jpillora/dnsmasq'
    ports:
      - "53:53/udp"
    volumes:
      - ./docker/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    environment:
      - "HTTP_USER=foo"
      - "HTTP_PASS=bar"

  rethinkdb:
#    ports:
#     - "28015:28015" # client driver connections
#     - "29015" # Intracluster connection
  
  pushpin:

  api:
    image: help/api/dev
    build: 
      dockerfile: ./dev.Dockerfile
    volumes: 
      - ./backend:/usr/src/help/api

  app:
    image: help/app/dev
    build:
      context: ./frontend
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/help/app
    ports:
      - "4200:4200"

  caddy:
    volumes:
      - ./docker/caddy/Caddyfile.dev:/etc/Caddyfile  # to mount custom Caddyfile

  
